// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZwalks.API.Data;

#nullable disable

namespace NZwalks.API.Migrations
{
    [DbContext(typeof(NZwalksDBContextcs))]
    [Migration("20250730161454_Seeding data for Difficulties and region")]
    partial class SeedingdataforDifficultiesandregion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZwalks.API.Model.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            ID = new Guid("335d8255-9953-4845-8581-788ac4e153d8"),
                            Name = "Easy"
                        },
                        new
                        {
                            ID = new Guid("f7ef4ca5-e069-49cc-9b39-1a90d1438418"),
                            Name = "Medium"
                        },
                        new
                        {
                            ID = new Guid("14491e4d-9abb-44af-8b56-701c0b06b09d"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZwalks.API.Model.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageurl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("311d028f-6801-40a1-85d9-32834d8f3e04"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageurl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIIodJ7L7jxCAiZHGLKTbNKYLND-vgPS3vbA&s"
                        },
                        new
                        {
                            Id = new Guid("f7109940-19f0-48d4-97fd-898942b0ade7"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageurl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6lhHopLJArrwJ4nyxk1AtR7m72M71_dFbVw&s"
                        },
                        new
                        {
                            Id = new Guid("a1cdec49-afa7-47b7-9584-f82252f37da6"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageurl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ9kBp01al31iWgPGCja8IOlWL1bG3RS2wLw&s"
                        },
                        new
                        {
                            Id = new Guid("fbd1b7d6-3308-42bb-a98e-2f1500c59673"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageurl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZjn1lpvZhzBjiTLktxnJ5xUM6qqIPabUtkQ&s"
                        });
                });

            modelBuilder.Entity("NZwalks.API.Model.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalksImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyID");

                    b.HasIndex("RegionID");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZwalks.API.Model.Domain.Walk", b =>
                {
                    b.HasOne("NZwalks.API.Model.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZwalks.API.Model.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
